-- Enable the pgvector extension
create extension if not exists vector;

-- Create a table for storing Vinted documents
create table if not exists vinted_documents (
  id bigint generated by default as identity primary key,
  content text,
  metadata jsonb,
  embedding vector(1536)
);

-- Create a function for matching documents
create or replace function match_documents (
  query_embedding vector(1536),
  match_count int default 5,
  filter jsonb default '{}'::jsonb
) returns table (
  id bigint,
  content text,
  metadata jsonb,
  similarity float
)
language plpgsql
as $$
begin
  return query
  select
    id,
    content,
    metadata,
    1 - (vinted_documents.embedding <=> query_embedding) as similarity
  from vinted_documents
  where metadata @> filter
  order by vinted_documents.embedding <=> query_embedding
  limit match_count;
end;
$$; 